### ISSUE TITLE
screenshots are duplicated when using ScreenShooterExtension and Allure

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1002]
See comment https://github.com/selenide/selenide/pull/946#issuecomment-507961860

## The problem
**Given** a project using
 * `com.codeborne.selenide.junit5.ScreenShooterExtension`
* Allure 

**When** a test fails
**Then** two screeenshots are takes.

## Details
1. `ScreenShooterExtension` takes a screenshot (and just logs it),
2. Then `ScreenShooterExtension` triggers Allure listener (via `SelenideLogger.commitStep`) which also takes a screenshot. 

It would be nice to avoid taking 2 screenshots.

## Tell us about your environment
* **Selenide Version**: 5.4.1

**Comment by SeleniumTestAB** [comment]
@asolntsev would it be hard to check if logger with name "allure" is present and make condition from it?

**Comment by asolntsev** [comment]
@SeleniumTestAB it's technically possible, but it doesn't seem to be a good idea in terms of design. Selenide core code should not depend on any listeners.
I would rather suggest that AllureListener could check if Selenide has already taken a screenshot during current test. Maybe we should even create a superclass for such listeners in Selenide.

**Comment by SeleniumTestAB** [comment]
@asolntsev indeed it seems that fix should be on allure side rather. As for superclass, doesnt SelenideLogger fulfill such role?

**Comment by dstekanov** [comment]
Hi @asolntsev, 
I was not able to reproduce this issue, and when I looked inside `ScreenShooterExtension` I did not find `SelenideLogger.commitStep` so seems this issue can be closed.

**Comment by asolntsev** [comment]
@dstekanov I haven't tried to re-reproduce it yet, but my logic says that
1. When `ScreenShooterExtension` works without Allure, it takes screenshot.
2. When Allure works without `ScreenShooterExtension`, it also takes screenshot. 
3. When `ScreenShooterExtension and Allure are both enabled, they both must take their screenshots (they don't call each other to ask if there is already screenshot taken). 

Am I right?

**Comment by dstekanov** [comment]
Now I see and seems it's not a problem with `ScreenShooterExtension` 

`ScreenShooterExtension` does not take (by default) screenshots for `UIAssertionError`.
So when such `non-UIAssertionError` happens, e.g. with `org.junit.jupiter.api.Assertions`,  `ScreenShooterExtension`takes a screenshot but it does not update status in LogEvent and Allure does not take a screenshot and there is no attachment in the report...

When we have `UIAssertionError`,  Selenide takes a screenshot and `ScreenShooterExtension` does not play a role here(because even without the extension it takes it) and Allure also takes a screenshot. So we really have 2 screenshots (1 in allure-results folder, another in reports folder)
