### ISSUE TITLE
WebDriverRunner.getSelenideDriver() is not public after 5.4.0

### ISSUE THREAD

**Issue by NilsHasenbanck4758** [selenide/selenide#1010]
#989 did changed `WebDriverRunner.getSelenideDriver()` to private. This change hasn't been documented in the release documentation, so the question is: Was this intentional?

What is the suggested replacement to access the underlying SelenideDriver?

**Comment by asolntsev** [comment]
@NilsHasenbanck4758 It was an intentional change. 
The reason is that nobody should ever need it (it was unintentional when we made in public in 5.0.0). 

Users should use class `SelenideDriver` explicitly only when they need to create two (or more) webdriver instances in one test (see https://selenide.org/2018/10/10/selenide-5.0.0/). In this case you have 2 local variables of type `SelenideDriver` in your test. You can use them, and thus you just don't need `WebDriverRunner.getSelenideDriver()`. 

If you still are sure that you need `WebDriverRunner.getSelenideDriver()`, please describe the case.

**Comment by NilsHasenbanck4758** [comment]
@asolntsev The SelenideDriver was a convinient wrapper, in my case primarely for the "clearBrowserLocalStorage()" function. Granted, it's easy to replace.

With SelenideDriver:
```kotlin
    WebDriverRunner.getSelenideDriver().clearBrowserLocalStorage()
```

Without SelenideDriver:
```kotlin
    WebDriverRunner.driver().executeJavaScript<Unit>("localStorage.clear();")
```

**Comment by asolntsev** [comment]
@NilsHasenbanck4758 Clear. I have good news for you: we have even better method for that.
Just use `Selenide.clearBrowserLocalStorage()` :)

**Comment by bmurmistro** [comment]
> If you still are sure that you need `WebDriverRunner.getSelenideDriver()`, please describe the case.

`UIAssertionError` is a nice way to capture diagnostic info. Without access to the `SelenideDriver`, `UIAssertionError` can't be used. For example,

```
  try {
      Selenide.Wait()...
  }
  catch (TimeoutException e) {
      throw UIAssertionError.wrap(noDriverHere, e, Configuration.timeout)
  }
```

**Comment by asolntsev** [comment]
@bmurmistro Thank you for the example. 

Yes, in this case you need an instance of `Driver`. But... `UIAssertionError.wrap` was never meant for public use. It's kind of "private" function for Selenide internal usage. 

But yes, I understand that it's a good idea to capture a diagnostic info. I need to think about it...

Could you please describe the case: why you need to call `Selenide.Wait()`? Ideally, Selenide users shouldn't use explicit waits because a "standard" way to do it is to use Selenide `Condition`s (either built-in or custom).

**Comment by bmurmistro** [comment]
> Could you please describe the case: why you need to call Selenide.Wait()? Ideally, Selenide users shouldn't use explicit waits because a "standard" way to do it is to use Selenide Conditions (either built-in or custom).

@asolntsev we have some custom scrolling logic that requires executing javascript. However, I do agree that we could achieve the desired results with a custom `Condition` instead of using `Selenide.Wait()`.
