### ISSUE TITLE
Add support for Shadow DOM

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1014]
###  The problem

Shadow DOM is used by any framework that supports web components. For example, when testing a Vaadin app with Selenium it can become necessary to look inside the Shadow DOM of some of the Vaadin web components. If you go to the Vaadin homepage and then click "Login" at the top right corner to make the login dialog appear, then look for the element with the id "login-username". It is a Vaadin web component, which models an input field, but the real input element is inside its Shadow DOM. If you open the #shadow-root element in the Firefox or Chrome inspector, you'll find a HTML input element inside. And that element is where I would like to enter my text in a Selenide test.

>  I saw an example implementation for a selector "ByShadowCss" on this Stack Overflow thread (last answer on page):
> https://stackoverflow.com/questions/23920167/accessing-shadow-dom-tree-with-selenium

See this thread for more details: https://groups.google.com/forum/#!topic/selenide/sCbHqePe13M

**Comment by dstekanov** [comment]
Hi @asolntsev! 
Is it a good idea to have such syntax `$(ByShadow.css("shadow-host >>> #search-button"));` ?

**Comment by asolntsev** [comment]
@dstekanov Hm... I don't know. What is current alternative for this selector?

**Comment by dstekanov** [comment]
I've experimented with it... and as I understood, in order to find elements inside the Shadow-DOM tree, first, we need to find the shadow host element to which the shadow dom is attached (so we got shadow-root element). 

I thought to make something like this: `$(Selectors.shadowCss("#shadow-host")).$("#element-inside-shadow-dom").shouldHave(text("some text"));`

First, to find shadow-host and return its shadow root. For example:
```
public WebElement findElement(SearchContext context) {
  WebElement result = ((FindsByCssSelector) context).findElementByCssSelector(cssSelector);
  return (WebElement) getJavascriptExecutor(context).executeScript("return arguments[0].shadowRoot", result);
}
```
This approach works in Chrome (I have a working copy for it)

But in Firefox `arguments[0].shadowRoot` returns the map with different attributes (not sure if I understand it completely), so the only way to start searching the element is to use  `arguments[0].shadowRoot.querySelector('target-element')` (it will work in both browsers)

As alternative, maybe something like this, because also we can have inner shadow-dom elements
`shadow$(target-element, shadow-host...).shouldHave(text("some text"));`

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/1090 (Selenide 5.10.0)
