### ISSUE TITLE
Parallel test running in testng and selenide

### ISSUE THREAD

**Issue by lsdkjflasjflkdasj** [selenide/selenide#1018]
## The problem
Parallel test runs in Selenide uses one global configuration
## Details
https://github.com/selenide/selenide/issues/354 and a couple of other issues, I've seen already.  It seems as though this feature is now implemented but I don't know how it works.  In the following code, only one type of browser is opened for ALL tests.  Whichever thread manages to set the browser configuration last, sets it for ALL tests.

## Tell us about your environment
* **Selenide Version**:  5.5
* **Chrome\Firefox\IE Version**:  Latest chrome/firefox
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**:  macosx

## Code To Reproduce Issue [ Good To Have ]
```java
package org.selenide.examples;
import com.codeborne.selenide.Configuration;
import org.openqa.selenium.By;
import org.testng.annotations.*;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;
import com.codeborne.selenide.testng.ScreenShooter;

@Listeners({ ScreenShooter.class})
public class GoogleTest {
    @BeforeGroups
    public void setUpTest() {
        open("https://www.facebook.com");
    }

    @Test
    public void testSelenide( ) {
        Configuration.reportsFolder = "test-result/reports";
        ScreenShooter.captureSuccessfulTests = true;
        Configuration.browser = "chrome";
        open("http://google.com");
    }

    @Test
    public void testParallel() {
        Configuration.reportsFolder = "test-result/reports";
        ScreenShooter.captureSuccessfulTests = true;
        Configuration.browser = "firefox";
        open("http://google.com");
    }

    @Test
    public void testAnotherParallel() {
        Configuration.reportsFolder = "test-result/reports";
        ScreenShooter.captureSuccessfulTests = true;
        Configuration.browser = "firefox";
        open("http://google.com");
    }
}
```

**Comment by asolntsev** [comment]
@lsdkjflasjflkdasj  In that sense, this feature is not implement in Selenide. `Configuration.browser` is still a static field. 
You have 2 options:
1. As described in https://github.com/selenide/selenide/issues/354, you can create a separate `SelenideDriver` instance in every test, and you it instead of static methods `Selenide.open` and `Selenide.$`. You will get thread-safe configurations, but code of your tests will be more polluted. 
2. (I recommend) to keep your tests as is, but parallelize differently. Just remove lines with `Configuration.browser` from your tests.

As long as I see, the only setting which is different in your tests is `Configuration.browser`. 
I think that it's a misuse of test parallelization. Instead, I recommend to create 2 different profiles (in Maven) or tasks (in Gradle): one for Firefox and other for Chrome. Then you will have 2 jobs in Jenkins: one for Firefox and other for Chrome. And the you will be able to run those jobs in parallel.
