### ISSUE TITLE
Search by/with text doesn't work on all elements

### ISSUE THREAD

**Issue by idomoni** [selenide/selenide#1046]
## The Problem
On page similar like domoni.net, buttons have this kind of structure:
![image](https://user-images.githubusercontent.com/42203202/73654628-8214fa00-468c-11ea-835e-768782a7187f.png)

So next script doesn't work and test will fail:
    	open("http://www.domoni.net/");
    	$(byText("SERVICES")).click();

Log:
![image](https://user-images.githubusercontent.com/42203202/73654806-e0da7380-468c-11ea-98c8-6f14c414fecc.png)

## Question or suggestion
You were stating that the best way to select element is to select it through text and that Selenide is the best for it. Cannot  agree more, but in this case is not working.
Could you make it possible in future, Selenide to recognize text, even in form like this one?

## Environment used for testing
* **Selenide Version 5.6.1
* **Chrome, FF

**Comment by asolntsev** [comment]
@idomoni Hi. There are several problems with your example:
1. You search by text "SERVICES" (uppercase), but the real text inside html is "Services" (lowercase). 
2. That's why this variant could work for you: `$(byText("Services")).click();`.
3. But it also doesn't help because there are 3 elements on this page with text "Services". Some of them are invisible. 
4. That's why this variant works for you: `$(byText("Services"), 1).click();` or `$(byText("Services"), 2).click();` (I am not sure which one did you really want to click). 
5. Searching by text has one risk: there always might be more than one element with such a short and widely used text as "Services".
6. That's why this variant is probably better: `$("#avia-menu").$(byText("Services")).click();`

**Comment by idomoni** [comment]
Thank you for this answer and solution/s.
Case sensitivity was not my main concern, but yes it would be good idea.
At least I learned new things like selecting which one to click $(byText("Services"), 1-n).click(); or to use $ twice as you suggested $("#avia-menu").$(byText("Services")).click()

Cheers mate,

**Comment by idomoni** [comment]
Hi @asolntsev ,
maybe you could also think about implementing logic that, 
in case of many elements on page with same locator or text in this case, and when is not defined which one to click on 1),2) ... Selenide should click on first one and not fail test. 
This logic works on Selenium.

**Comment by asolntsev** [comment]
@idomoni Hi. Yes, Selenide method `$` does exactly this: finds the first matched element.
In your case, there was no matching elements - that's why the test failed.
