### ISSUE TITLE
Add support for dynamic locators in page objects with @FindBy annotations

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1050]
### Background
Selenide allows to use page objects with annotations like `@FindBy`:

```java
  @AndroidFindBy(id = "op_add")
  @iOSFindBy(id = "op_add")
  private SelenideElement plus;
```

### The problem
It doesn't allow using of dynamic locators (when "op_add" is not a compile-time constant, but needs to be calculated in runtime).

### Suggestion
Selenide could allow using dynamic locators by such an API:

```java
  @AndroidFindBy(id = "opa_${zopa}")
  @iOSFindBy(id = "${zopa}_opa")
  private SelenideElement plus(String zopa);
```

In this case, `plus` would me method, not field - which is even better in terms of page object idea.
And Selenide would need to create a "proxy" object implementing this method on-the-fly. 

@BorisOsipov @rosolko @yashaka What do you think?

**Comment by yashaka** [comment]
IMHO all this "FindBy" annotation-based syntax is "magical", and not straightforward. 
Moreover @FindBy comes from PageFactory of Selenium Webdriver, where PageFactory was deprecated, correct me If I am wrong regarding deprecation....

I prefer more straight forward style of elemet definition, like:
```
foo = $("#foo);
```

In case of Mobile, on my projects, I have implemented a wrapper over SelelenideElement, that allows the following style:

```
foobar = drd("foo").ios("bar");
```

I find this style more straightforward, obvious and oop-natural. And more powerful. You can then build your PageObjects like you want as normal java objects. 

So I would deprecate FindBy at all:)

**Comment by jreznot** [comment]
@yashaka Why do you think PageFactory is deprecated? 
I see no evidence of it https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/PageFactory.html

**Comment by jreznot** [comment]
@asolntsev 
> And Selenide would need to create a "proxy" object implementing this method on-the-fly.
This requires byte-buddy or javassist dependency as Proxy from JDK does not support classes.

**Comment by yashaka** [comment]
@jreznot, I heard about such plans, a few years ago...
Since then, it [actually happened](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG#L187) for the dot net version of webdriver implementation:
![image](https://user-images.githubusercontent.com/1961118/81480582-482b3500-9233-11ea-973b-8d72d2552b65.png)

@barancev, can you help to clarify this topic?

**Comment by jreznot** [comment]
.Net webdriver is not the source of truth. Most likely, they deprecated PageFactory due to lack of resources of the maintainer. BTW, from my POV .Net is used for < 5 % of Selenium test projects

**Comment by jreznot** [comment]
http://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html?m=1

> In the case of the .NET PageFactory, the implementation was problematic and cumbersome, as well as not nearly flexible enough for the myriad ways people wanted to create Page Objects. Additionally, when .NET Core 2.0 was released, the classes upon which the .NET PageFactory relied were not included .NET Core 2.0. This meant that to get the PageFactory working under .NET Core, the project either had to take on a new dependency, mangle the code with conditional compile directives, or leave it unsupported in .NET Core. The first approach is a non-starter for the Selenium project's .NET bindings, the reasons for which should be a subject of its own blog post. The second approach made the code nearly impossible to properly maintain.

**Comment by yashaka** [comment]
Maybe I messed it up with only net specifics. Let's see. I will try to get more info from the original sources where I heard this. Your links already clarifies a lot of things... Thank you. Let's see...

**Comment by barancev** [comment]
`PageFactory` implementation (and `FindBy` annotation that is a part of it) is not deprecated in Java binding and is not going to be deprecated in near future.

**Comment by vinogradoff** [comment]
> ```
> foobar = drd("foo").ios("bar");
> ```
> 
> I find this style more straightforward, obvious and oop-natural. And more powerful. You can then build your PageObjects like you want as normal java objects.
> 
> So I would deprecate FindBy at all:)

I also like the simple java calls more, some ideas for handling it for Kotlin style $m (mobile-abled locator) with up to 3 optional parameters common, android, ios:

```
  val plus = $m("#opp_add")
  val plus = $m("#opp_add", android="#opp_android")
  val plus = $m("#opp_add", ios="#opp_ios")
  val plus = $m(ios="#opp_ios", android="#opp_android")
```

It can be done similary in Java with method overloading

**Comment by jreznot** [comment]
@vinogradoff `$m` will not compile in Kotlin. Only with ``` `$m` ```.

**Comment by vinogradoff** [comment]
I know, it's supposed to be just pseudo-code

**Comment by yashaka** [comment]
So...
I have to admit, that I was wrong in my thinking of "FindBy will be deprecated in Java". Seems like I misunderstood, and the deprecation was relevant only for dot net. 

@barancev , thank you for the clarification! 
@jreznot , thank you one more for bringing the topic up.

Since @FindBy is one of the standard ways in many enterprise-like cases, then it seems reasonable to keep it in Selenide (since it's already there... though I think that in general such things are better to be kept as separate addons/plugins, not as a core part, but this is also just one of subjective preference)

Then it seems to be reasonable to extend also @Android/iOSFindBy support in the context of dynamic locators as proposed in the original Andrei's suggestion. At least it should not make worse but it seems to be helpful for those who use this style... 

Just then for consistency, it would make sense to extend original @FindBy too... 

Regarding something like

```
val foobar = drd("foo").ios("bar");
```

or 

```
  val plus = $m("#opp_add")
  val plus = $m("#opp_add", android="#opp_android")
  val plus = $m("#opp_add", ios="#opp_ios")
  val plus = $m(ios="#opp_ios", android="#opp_android")
```

Probably this is a different topic, that can be considered outside of this issue... Maybe in another... Actually to really reflect all mobile needs I would create separate SelenideMobileElement. I am not sure it makes sense to try to cover everything in SelenideElement...

**Comment by asolntsev** [comment]
See similar suggestion here: https://github.com/selenide/selenide/issues/1386

**Comment by asolntsev** [comment]
it seems we can close it because people didn't like the idea.
