### ISSUE TITLE
Configure capabilities of selenium from Selenide.

### ISSUE THREAD

**Issue by 1304julian97** [selenide/selenide#1068]
## The problem
Hello everybody, I have been working with Selenide, and I need to configure some things, for example, the default folder of download files, SSL certified. These things I know that I can update or create from selenium directly, but I do not know, how can I do from selenide?

## Details
I needed to use selenium native to create these configurations, and after that, I should mix selenium native and selenide to can apply these changes.

## Tell us about your environment
* **Selenide Version**: "com.codeborne" % "selenide"  % "4.10" % "test" (sbt code )
* **Chrome Version**: Versión 80.0.3987.116 (Build oficial) (64 bits)
* **Browser Driver Version**: 
* **Selenium Version**: -
* **OS Version**: Windows 10 PRO

## Code To Reproduce Issue [ Good To Have ]
![image](https://user-images.githubusercontent.com/20733187/75052469-aac72d00-549d-11ea-81e9-f5d0d58325b2.png)

In this code, I could apply the changes, but I think that is not a good form. 

Thank you in advance.

**Comment by asolntsev** [comment]
@1304julian97 Your code is ok. It's a normal way to setup webdriver with your custom settings. 

The only advice is to use `WebDriverProvider` instead of `WebDriverRunner.setWebDriver`. See https://selenide.org/2019/12/03/advent-calendar-set-webdriver-vs-webdriver-provider/ for explanation. And https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver
