### ISSUE TITLE
compare with cypress

### ISSUE THREAD

**Issue by ycwdaaaa** [selenide/selenide#1216]
I'm sorry to ask this question, but I really want to know if cypress is better than selenide. what I know is cypress is able to wait UI components by default, but selenide has the same feature.   And like assertion or more selectors, I found selenide  has these feature too. So why so many people said cypress will replace selenium,  selenium will be obsolete.  PS: I found cypress has more starts in github.

**Comment by asolntsev** [comment]
I think both Selenide and Cypress have features like "automatic waiting" etc. 

In some sense, Cypress is simpler than Selenium, but it's also limited (it cannot open multiple windows, cannot run remote browser, cannot use Grid etc.). If these features are needed in your project, Cypress just doesn't suite for you.

I think people want to migrate to Cypress because they don't like WebDriver infrastructure: the need to download webdriver binaries etc. Or they just don't like Java. :) For those who don't program in Java, it's especially hard to run a separate Java server ("Selenium Grid") just to run tests. 

So, my conclusion:
1. For non-Java programmers and simple projects Cypress is probably better
2. For Java programmers, Selenide is also pretty simple to run. No harder than Cypress.
3. For complex projects that need remote browsers, grid, proxy etc. Cypress doesn't suite.
