### ISSUE TITLE
Feature Request: Highlight active element

### ISSUE THREAD

**Issue by fkrivsky** [selenide/selenide#1277]
## The problem
Please add a configuration option that would by default highlight element that's being interacted with. 

## Details
It is possible to highlight elements with JavaScript executor ([example1](https://www.softwaretestingmaterial.com/highlight-element-using-selenium/) or [example2](https://stackoverflow.com/questions/10660291/highlight-elements-in-webdriver-during-runtime)).
However that AFAIK would require writing a wrapper for each Selenide method...
Is it possible to have a Configuration switch that would do this for all actions where it makes sense?

**Comment by asolntsev** [comment]
Hi @fkrivsky !
We also have some examples of highlighting elements:
* [selenide-examples -> gmail](https://github.com/selenide-examples/gmail/blob/master/test/org/selenide/examples/gmail/Highlighter.java)
* https://selenide.org/2019/12/06/advent-calendar-visualize-click/

I am afraid that making a universal "highlighter" is hard because it heavily depends on the design and behaviour of AUT. 

Thought, any suggestions are welcome.

**Comment by lemitrou** [comment]
Is one of the most useful feature in a test framework, I've seen it in action, and i definitely say that every stakeholder - dev -product manager - qa, loved it for different reasons.

For the "paint" work, we will use Javascript. Something like `style.backgroundColor` will do want we want
And also i would expect a configuration parameter e.g `Configuration.highlight=true`, also for backwards compatibility.

Since selenide has already plenty assertion functions, i believe that will not so much effort a few overloading methods - this just an assumption of course.
 
May be is a good idea to start a PR!!!!

**Comment by asolntsev** [comment]
I also think it might be useful, at least for debugging flaky tests.
But probably it's better to implement this feature as a separate Selenide plugin. Then it can have its own configuration, and can override some of Selenide default methods.

**Comment by lemitrou** [comment]
@asolntsev do you have any guide of how to create a selenide plugin?? I'll start in my project , that uses selenide, to introduce a more scalable and professional solution for highlighting, and I think it's better to do it in selenide framework level giving the opportunity to use from other as well.

**Comment by asolntsev** [comment]
@lemitrou It's easy to see how existing plugins are implemented:
* [clear-with-shortcut](https://github.com/selenide/selenide/tree/master/modules/clear-with-shortcut)  - overrides methods `$.clear()` and `$.setValue()`
* [full-screenshot](https://github.com/selenide/selenide/tree/master/modules/full-screenshot)  -  overrides method `Selenide.screenshot()`.

**Comment by asolntsev** [comment]
I added method `$.highlight()` in PR https://github.com/selenide/selenide/pull/2481
