### ISSUE TITLE
`WebDriverRunner.getBrowserDownloadsFolder()` returns `null` when 'selenide.remote` enabled

### ISSUE THREAD

**Issue by imaksymiv** [selenide/selenide#1387]
## The problem
When running tests via Selenoid, it's required to download files from a container. 
For `Selenide 5.15.1` download was happening to the folder we could get via `WebDriverRunner.getBrowserDownloadsFolder()`.
For the Selenide version specified below, `WebDriverRunner.getBrowserDownloadsFolder()` returns `null` when a method tries to determine a folder to download the file.

## Tell us about your environment
* **5.18.0**: 
* **Chrome 88.0**:

**Comment by asolntsev** [comment]
Yes, it's reasonable because "BrowserDownloadsFolder" only applies to local browser. In case of remote browser, we don't know what folders exist on the remote machine. 

Why do you need this value? How can you use it, if the folder is located on another machine anyway? 

P.S. If you run browser in Selenoid, we have specific support in [selenide-selenoid](https://github.com/selenide/selenide-selenoid) module.

**Comment by imaksymiv** [comment]
My scenario is the following:

1. Obtain the unique for the current session folder
2. Download file from Selenoid to that folder (FileUtils.copyURLToFile)

For `Selenide 5.15.1` the folder wasn't null for such kinds of scenarios.

**Comment by asolntsev** [comment]
@imaksymiv Clear, thanks.
I suggest just to use [selenide-selenoid](https://github.com/selenide/selenide-selenoid) dependency. It does exactly what you need. You can use the old good Selenide method `$.download()`, and `selenide-selenoid` will fetch the file from Selenoid container and save to a unique folder on your machine.
