### ISSUE TITLE
Feature Request: expose .because() clause in LogEvent

### ISSUE THREAD

**Issue by mszajowskiwr** [selenide/selenide#1396]
## The problem
The `LogEvent` that comes from `should()` calls should somehow contain `message` that has been set via `because()` call on the `Condition` used in the `should()`.

## Details
`io.qameta.allure.selenide.AllureSelenide` listener does a great job of putting events from Selenide into its report, but it cannot reach the `message` of `ExplainedCondition`. Would be great to have the whole `Condition` exposed in the `LogEvent` and `ExplainedCondition` exposing the `message` field value . That way, allure's `Step`s in report would be able to show `because()` details in theirs `Step`s.

**Comment by asolntsev** [comment]
@mszajowskiwr Are you asking for a method `LogEvent.getBecause()`? 
Are you sure you really need it? I see that method `LogEvent.getSubject()` already contains the "because" part.

For example, this line in tests:
```java
$("#username").shouldBe(visible.because("FOO"));
```

generates such a line in report:
```
|#username           |should be(visible (because FOO))                                     |
```

In this case, `logEvent.getSubject()` returns `should be(visible (because FOO))`.

**Comment by mszajowskiwr** [comment]
Yes. Truth be told, I could parse the string for "should" or "wait until" and use it. However this seems to be somewhat of a hacky solution. I undestand, that exposing `ExplainedCondition` would not be that easy, architecture-wise?

**Comment by asolntsev** [comment]
@mszajowskiwr no, the question is not that it's hard. The question is why you need it? Why do you need to parse this string?

**Comment by mszajowskiwr** [comment]
Default `AllureSelenide` listener logs every event so the report becomes very noisy.

For example, if I have a page object with `SelenideElement someElement = $("something").parent()`, allure will include this initialisation in the report:

![image](https://user-images.githubusercontent.com/56036647/107969043-781c1b80-6faf-11eb-9219-d08ce76aa724.png)

The above came from:
```java
    @Test
    void someTest() {
        SelenideElement someElement = $("something").parent();
        open("https://google.pl");
        $("foo").shouldNot(Condition.exist.because("that should not exist"));
        $("baz").waitUntil(not(Condition.exist.because("that also should not exists")), 5000);
        $("bazinga").should(not(Condition.exist));
        $("bar").should(Condition.exist.because("and this should fail"));
    }
```

I want to filter out the noise and have only business-defined `@Step`s and meaningful assertions in the report. For now, with my custom listener, I'm only including events that match `event.toString().contains("because")` - that way my report contains only `@Step`s and assertions. 

However, it will also include `SelenideElements` that have locators that contain string `"because"` in them. That's what I meant by "hacky" - we don't really know if the `should` made a business-meaningful event or not. And we define such `should`s by adding `because()` to them.

It's all about making the report digestible for non-technical staff.

**Comment by asolntsev** [comment]
@mszajowskiwr Thank you for the clarification. 
Well, the fact that `$.parent()` gets to the report is rather a Selenide bug. The idea was that only "actions" and "checks" should get to the report, but methods like `find`, `parent`, `closest` etc. should not. Probably it's better to fix this bug instead of creating tricky solutions? ;) 

It also seems to me that you don't really need `AllureSelenide` listener. Instead, you probably prefer to mark all needed methods with `@Step` annotations to generate report only from them. 

P.S. And finally, in my personal opinion, we should never bother about "reports for non-technical staff". People often think that "non-technical staff" will read their reports, but they actually don't read. Ask yourself:
1. how much does it cost to generate&maintain such reports (including your time, resources, salaries etc), and
2. how much money the company will loose if these reports would be rather technical.

In #2, I think the answer is (almost always) "0".

**Comment by mszajowskiwr** [comment]
@asolntsev Our SEO team is using reports as part of acceptance criteria and they do look into those. With `@Step`s only, they won't see what are the assertions being made. And reporting each `should()` introduces too much noise (like exposing page object logic to allure report).

We'll keep the `event.toString().contains("because")` then. Thank you for your input!
