### ISSUE TITLE
Feature Request: Integrate Axe-core Api

### ISSUE THREAD

**Issue by anilreddy** [selenide/selenide#1484]
## The Feature Request
Hi I came across this API and it is useful for may of us so could you please check to integrate it with selenide.
It is an [axe-core](https://github.com/dequelabs/axe-core) api for accessibility testing and is already integrated with selenium.

List of project already using axe api
https://github.com/dequelabs/axe-core/blob/develop/doc/projects.md

**Comment by rosolko** [comment]
@anilreddy, thanks for proposal, but:
There are no plan to integrate selenide with such tools. 
We don't wan to overload library with 3rd party tools.
All of because there are many of it and each project requires different set of additional libraries and we can't integrate and support all of them.
Let's end use decide what to choose on their side.
As for now we wrap selenium with a little modification such a browser inariese download, configurable proxy and improved syntax, reusable and suitable for most of selenium projects.
Your proposal extend in a custom project specific way.

**Comment by asolntsev** [comment]
@anilreddy Yes, I don't think we will add it to the Selenide core, but we can build a special Selenide plugin for `axe-core` (like we already have Selenide plugins for Appium and Selenoid).

**Comment by anilreddy** [comment]
@asolntsev That would be great..!!

**Comment by asolntsev** [comment]
@anilreddy You can always send a pull request ;)
