### ISSUE TITLE
There should be a direct way to get shadowRoot of an element

### ISSUE THREAD

**Issue by angryziber** [selenide/selenide#1515]
## The problem

Selenide includes strangely named `shadowCss()` selector, but it cannot be used to access element's shadowRoot itself, only search for elements from within of the shadowRoot.

I propose to rename `shadowCss()` to e.g. `inShadowOf("sub-selector", "shadow parent selector")`, but also to introduce `SelenideElement.shadowRoot()` for consistency with DOM API, so it would be possible to select an element, resolve it's shadowRoot and then continue searching using `find()` with any possible means, e.g. `$("web-component").shadowRoot().find(withText("Hello"))`

## Tell us about your environment
* **Selenide Version**: 5.23.0

**Comment by asolntsev** [comment]
@angryziber We can add method `shadowRoot()`, but it will not help because search by XPath doesn't work inside of a shadow root. See bug https://github.com/SeleniumHQ/selenium/issues/5869.

For example,
1. `$("web-component").shadowRoot().find("div.active")`  --  works
2. `$("web-component").shadowRoot().find(withText("Hello"))`  --  fails with `InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression ... NotSupportedError: Failed to execute 'evaluate' on 'Document': The node provided is '#document-fragment', which is not a valid context node type.`

**Comment by asolntsev** [comment]
UPD Method `$.shadowRoot()` was removed in Selenide 6.1.0,
See PR https://github.com/selenide/selenide/pull/1641 and https://github.com/selenide/selenide/issues/1640.
