### ISSUE TITLE
Problem with searching by shadowDOM, when working directly with host element

### ISSUE THREAD

**Issue by AlbertGabdullin** [selenide/selenide#1550]
## The problem
I have not found the method to search by shadowDom, when I work directly with the host element. Just a couple of examples.
Selenide has the method `ByShadow.cssSelector(_target_, _shadowHost_).`
I have the variable like
`val hostElement = $(By.xpath("//some-web-component"))`
If I want to find some element inside the shadow DOM of our component, I have to go first to the parent and start searching from the parent element.
Example:
`
val found = hostElement.parent().$(ByShadow.cssSelector('.target-element', 'some-web-component'))
`
I would like to have the feature for ByShadow.cssSelector method when you can miss shadowRoot parameter if you work directly with the host element. Or if possible it would be great to have a separate method to work only with the host element.
Example:
`val found = hostElement.$(ByShadow.cssSelector('.target-element'))`

## Tell us about your environment
* **Selenide Version**: 5.24.1

**Comment by asolntsev** [comment]
@AlbertGabdullin Do I correctly understand that it's similar to https://github.com/selenide/selenide/issues/1515? We even have PR https://github.com/selenide/selenide/pull/1517 for it, but it seems to be useless because [searching by XPath doesn't work inside of Shadow Dom](https://github.com/selenide/selenide/issues/1515#issuecomment-894476289).

**Comment by asolntsev** [comment]
@AlbertGabdullin I hope this issues is closed by PR #1517 in Selenide 5.25.0
Feel free to reopen if new information arrives.
