### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/net/HostIdentifier

### ISSUE THREAD

**Issue by OldEngineer1911** [selenide/selenide#1669]
Hi, I would like to have selenide next to spring-boot project. Exact details can be found here, but I am not able to open page from the repository. It fails in the open() method.

What I did:

- Start simple SprigBoot project
- Add Selenide dependency, based on quick start: https://selenide.org/quick-start.html
- Tried to use it, also based on a quick start guide
- Pushed source code to github

Please take a look at the repository: https://github.com/OldEngineer1911/demo 
- I would like to add more details, but I am not sure if they are needed?

- Selenide 6.1.1
- SpringBoot 2.6.1
- Java 17
- Using JUnit
- Chrome version 96.0.4664.110 (Official Build) (64-bit)
- Windows 10

Can someone please help me?

**Comment by asolntsev** [comment]
@OldEngineer1911 Thank you for providing a working code which reproduces the problem! It's the best way you can help maintainers. 

In your case, the problem is caused by dependencies conflict. 
1. You are using Selenide 6.x which requires Selenium 4.+
2. But you are using Selenium 3.x

Next time you can just run `gradle dependencies` to see the problem. 
See https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/ for more details.
