### ISSUE TITLE
calling to the method element.should(disappear, timeout) takes long time even if the element is not present at the beginning.

### ISSUE THREAD

**Issue by jinlxz** [selenide/selenide#1683]
## The problem
calling to the method element.should(disappear, timeout) takes long time even if the element is not visible at the beginning of the call.
## Details
I found the following codes took about 30seconds to finish,  the element is not present on the page, I think the test should pass immediately as the Condition `disappear` is satisfied at the beginning of the call, why does it take so long time to execute? 
```java
        Selenide.open("https://www.microsoft.com/en-us/");
        SelenideElement overlay = $("#dummy_element_id");
        long start=System.currentTimeMillis();
        overlay.should(Condition.disappear, Duration.ofMillis(10000));
        System.out.println(String.format("the execution duration is %d millisecond", System.currentTimeMillis()-start));
```
the console output is as follows
```
the execution duration is 30035 millisecond
```
## Tell us about your environment
* **selenide core 6.0.3**: 
* **Browser Version 96.0.4664.110**: 
* **Browser Driver Version: v95**: 
* **Selenium Version 4.0.0**: 
* **OS Version windows10 64bit**: 

## Code To Reproduce Issue [ Good To Have ]
```java
public class SelenideTest {
    @Test
    public void testSelenideWait(){
        Selenide.open("https://www.microsoft.com/en-us/");
        SelenideElement overlay = $("#dummy_element_id");
        long start=System.currentTimeMillis();
        overlay.should(Condition.disappear, Duration.ofMillis(10000));
        System.out.println(String.format("the execution duration is %d millisecond", System.currentTimeMillis()-start));
    }
}
```

**Comment by BorisOsipov** [comment]
>why does it take so long time to execute?

Because somewhere in your code that you don't share with us you write smth like that:
`WebDriverRunner.getWebDriver().manage().timeouts().implicitlyWait(Duration.ofSeconds(30L));`
Selenium enables implicitly wait and every find call for unexciting element costs 30 seconds.

if you ran exactly piece of code you shared you will see no extra timeouts.
E.g.
![image](https://user-images.githubusercontent.com/6514276/148401355-1a5b8f48-4eee-4fbe-90d4-9a8fc6beb34e.png)


Can you check your code and completely disable any implicitly waits. You don't need it with Selenide.

**Comment by jinlxz** [comment]
Thank you @BorisOsipov , you are right, I use the `implicitWait` somewhere else, it's my fault.
