### ISSUE TITLE
interference between implicitWait and Configuration.timeout

### ISSUE THREAD

**Issue by jinlxz** [selenide/selenide#1684]
I used Selenide API in a legacy Selenium project, the Selenium `implicitWait` is used in the legacy project, now I can not disable the `implicitWait` simply, so my tests are mixed with `implicitWait` and Selenide dynamic wait defined by `Configuration.timeout`, I want to know how the two approaches interfere with each other, I don't find any helpful documentation about this. 

```java
$("#button1").shouldBe(disappear);
```
1. first the method `shouldBe`  need to locate the element, is the timeout for this step determined by `implicitWait` or `Configuration.timeout`
2. then it checks until the element disappear, which one determines the timeout for this step or the larger one of them?

could you help me with the above questions?

**Comment by asolntsev** [comment]
@jinlxz Do you use the same webdriver instance in legacy code and Selenide? 
(I assume people usually use one webdriver in legacy tests, and another webdriver instance in Selenide tests)

**Comment by jinlxz** [comment]
@asolntsev Yes, I  use the same webdriver instance, and in legacy code there are lot of statements like `driver.findElement(by);`, these statements will be impacted if I disable `implicitWait`.

**Comment by asolntsev** [comment]
@jinlxz I am afraid there is no an easy option. Implicit wait is a global setting which affects all interactions with the webdriver. 

The good news is that you probably don't need a big implicit timeout in most cases. 
Probably you could 
1. set a smaller implicit wait,
2. look all tests that fail because of that (I hope there should be a few of such places that really need a long timeout - like waiting for loading a very slow page)
3. use Selenide "waiting" methods in these places - like `$("#some-id-on-very-slow-page").shouldBe(visible, Duration.ofSeconds(60));`.
