### ISSUE TITLE
Selenide 6.9.0 - 6.10.0 issue with SelenideProxyServerClass

### ISSUE THREAD

**Issue by Panwo** [selenide/selenide#2031]
createSeleniumProxy() method triggers BrowserUp lib method which accepts **BrowserUpProxy** and **InnetAdress** objects as parameters. 

guessHostName returns String instead of InnetAdress which causes an exception during initialization.

Reproducible with browserUpProxy versions 2.0.1 - 2.1.2 

![изображение](https://user-images.githubusercontent.com/16680623/203531195-812cd4da-7dd8-4322-ac45-1d70487ded5a.png)

**Comment by BorisOsipov** [comment]
@Panwo 

Show your dependency tree. Seems you have old or unsopported version of browserup-proxy-core

**Comment by asolntsev** [comment]
released Selenide 6.10.1

**Comment by Panwo** [comment]
I can`t copy the dependency tree output from a VDI. Here is the browser up dependency 

![изображение](https://user-images.githubusercontent.com/16680623/203860275-53284347-5c3c-459f-beb2-65da26dff009.png)


@asolntsev 
https://mvnrepository.com/artifact/com.browserup/browserup-proxy-core
Is it the correct repo?  I don`t even see 2.2.3 version there.

**Comment by asolntsev** [comment]
@Panwo Yes, this is a wrong dependency. BrowserUpProxy was moved to another github account (see my link above). 
But you don't really need to declare "bup" dependency in your project. Instead of this, just add `implementation "com.codeborne:selenide-proxy:6.10.1"`. It will always fetch the needed BUP version.
