### ISSUE TITLE
Configuration.browserSize setting is ignored with custom WebDriver 

### ISSUE THREAD

**Issue by Zaykona** [selenide/selenide#2129]
When using customize WebDriver creation by:  "Extend WebDriver implementation, override public XxxDriver(Capabilities capabilities) constructor and pass this class name as browser system variable value" - Configuration.browserSize not overriding default ChromeDriver value and ignored.  Worked fine with Selenide 5

```
public class ChromeDriverProvider implements WebDriverProvider {
    @Nonnull
    @Override
    public WebDriver createDriver(@Nonnull Capabilities capabilities) {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--no-sandbox", "--disable-gpu", "--ignore-certificate-errors", "--disable-extensions",
                "--disable-dev-shm-usage", "clickViaJs");
return new ChromeDriver(options);
    }
```

```
 @Test
    public void openGoogle() {
        Configuration.browser = ChromeDriverProvider.class.getName();
        Configuration.browserSize = "800x600";
        Configuration.headless = false;

        open("https://google.com/");
        System.out.println("Real size: " + WebDriverRunner.getWebDriver().manage().window().getSize());

    }
```

Output: 
Real size: (1200, 921)

Environment:
Selenide version 6.11.0 
Chrome version 109
MacOs 13.1

**Comment by asolntsev** [comment]
@Zaykona Works as expected :) 
That's the point of custom webdriver provider: when you decide to implement it, you fully control the creation of the webdriver. You need to set all the properties by yourself. 

Yes, before Selenide 6.10.0, setting `Configuration.browserSize` affected also webdrivers created by custom `WebDriverProvider`s - but it was a bug. :) 

The fix is very easy for you: just add `--window-size=1800x1400` to your chrome options.

**Comment by Zaykona** [comment]
Yes, I have already added the fix. But it was interesting to understand the flow in general. Thank you for details. Got it;)
