### ISSUE TITLE
Filter and download files by extension

### ISSUE THREAD

**Issue by Soumendu-Khilar** [selenide/selenide#2143]
## The problem
I have a list of files in a webpage with extension pdf, zip and gz to download from a website. Is there a way in selenide to download only the pdf files from this list.
I tried downloading in Chrome using:
```java
$().download(using(HTTPGET).withFilter(withExtension("pdf")). 
```

However, it still downloads the files with zip and gz.
**Is withExtension not supposed to filter based on the extension?**

## Tell us about your environment
* **Selenide Version**: 6.10.1
* **Chrome Version**:  109.0.5414.87
* **Browser Driver Version**: 109.0.5414.74
* **Selenium Version**: 4.6.0
* **OS Version**:

**Comment by asolntsev** [comment]
Hi @Soumendu-Khilar 
1. `withExtension("pdf")` is needed when you download files using `FOLDER` or `PROXY` methods. Because in these methods, the browser can receive multiple downloads at the same moment, and needs to choose one of them. That's where filter may help.
2. But when you download the file using `HTTPGET` method, Selenide downloads the single file explicitly using URL. The single URL cannot trigger downloading multiple files. That's why filter is not needed here. 

If calling `$("#button1").download()` triggers downloading `zip or gz`, it means that you chosed the wrong button.
