### ISSUE TITLE
Open new page after each @Test

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2200]
## The problem
Dear all forumer, @asolntsev recommend open new page after each tests. I wonder how this can be implemeted. @asolntsev say open and close a web browser is slow. I'm totally begginer in selenide. Please provide some sample code. 

## Tell us about your environment
* **Selenide Version**:  6.12.1
* **Chrome\Firefox\IE Version**:  111
* **Browser Driver Version**: 
* **Selenium Version**: 4.8.1
* **OS Version**: CentOS 9 Stream

**Comment by asolntsev** [comment]
@nicholaswkc34 You can always find working examples in [Selenide own tests](https://github.com/selenide/selenide/tree/main/statics/src/test/java/integration). 

1. I recommend to avoid re-opening browser for every test because it's slow.
To achieve tests independence, you can add few lines in `@BeforeEach` method:
```java
  Selenide.localStorage().clear();
  Selenide.sessionStorage().clear();
  open("about:blank");
  // and probably clean some other resources
```
2. If you insist on reopening a browser before every test, you can use `BrowserPerTestStrategyExtension`. 
Or just add one line to `@BeforeEach` method:
```java
  Selenide.closeWebDriver();
```
