### ISSUE TITLE
Detect clicking a link open new tab

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2201]
## The problem
Dear all forumers, I had an advertising website from the company. This website has many links. I need to click some of them and detect clicking a link whether it open a new tab or stay in the current tab. 
How to detect clickng a link open a new tab or stay at current tab?

## Tell us about your environment
* **Selenide Version**: 6.12.1
* **Chrome\Firefox\IE Version**: 111
* **Browser Driver Version**: 
* **Selenium Version**: 4.8.0
* **OS Version**: Centos 9 Stream

**Comment by asolntsev** [comment]
@nicholaswkc34 It's a strange wish, I would say. Why do you want to test it? 
Anyway, 
1. you cannot be sure that the click opens the new page in the same tab (because user can click with Cmd or Shift)
2. you cannot be sure that the click opens the new page in a new tab (because I guess user can configure browser to open links in the same tab)

Anyway, you can try something like this:
```java
  int tabsCount = WebDriverRunner.getWebDriver().getWindowHandles();
  $("#theButton").click();
  Selenide.webdriver().shouldHave(numberOfWindows(tabsCount + 1));
```
