### ISSUE TITLE
$$(".my-elem").shouldBe(empty) is always true

### ISSUE THREAD

**Issue by realulim** [selenide/selenide#2323]
If you have an ElementsCollection of n elements (n > 0), then a test like

`$$(".my-elem").shouldBe(empty);`
`$$(".my-elem").shouldHave(size(n));`

might not fail. This is perhaps because the size() method doesn't wait for the collection to load.

There is probably a valid reason behind that, but logically the above code is contradictory and should not work. Or perhaps Selenide should provide an API for verifying the emptiness of an ElementsCollection (perhaps by waiting for the timeout and counting then).

**Comment by asolntsev** [comment]
> perhaps because the size() method doesn't wait for the collection to load.
All Selenide checks (aka conditions) **do wait** if needed. In that sense, checks `$$.shouldBe(empty)` and `$$.shouldHave(size(0))` are equal. 

If Selenide method `$$.shouldBe(empty)` waits for 4 seconds then it makes all tests much slower.

Essentially it's the same as if you just add `sleep(4000)` in your test before `$$.shouldBe(empty)`.

But I would say this question is rather about test design. Checks like `shouldNot(exist)` and `shouldBe(empty)` are always dangerous because they may give false positive if you occasionally use an invalid locator, or the element is not not loaded yet. In such cases, it's recommended to first perform some positive check (like, `$("#newPageHeader").shouldBe(visible)`) to be sure that the previous action has fully completed and everything is loaded. And only then you can perform `$$.shouldBe(empty)`.

**Comment by realulim** [comment]
Well, $$.shouldBe(empty) is an API, so I think it's not correct to say it shouldn't be used. You can abolish this API function, if you think it does more harm than good, but if it's there and supported, then we can discuss how it should work.

As for usage, imagine a situation, where a table is loaded with rows. Then there might be a situation, where no rows are loaded, perhaps in response to a certain user action. So how should it be tested that no rows are loaded? I know I can add my own sleep command before the empty-check, but my point is that there is no situation imaginable, where I would NOT want to do that and therefore a shouldBe(empty) in the current form appears to be of little use. And consequently it would not hurt anyone, because there can't really be any tests out there using it.

Also, isn't it the case that shouldHave(size(1)) waits for four seconds and shouldHave(size(0)) doesn't? Isn't that then inconsistent in itself?

**Comment by asolntsev** [comment]
> shouldHave(size(1)) waits for four seconds and shouldHave(size(0)) doesn't?

@realulim  It's not true. **Both** `size(1)` and `size(0)` **do wait** if needed (maximally 4 seconds). 

> it's not correct to say it shouldn't be used.

No, I didn't say it shouldn't be used. It can be used. I use it in my projects.
I just said that you need to understand how to use it safely - as any other tool.

> shouldBe(empty) in the current form appears to be of little use
No, I am not agree with this statement. Sure it's useful. Sure, it's useful - if used properly.


Once again, the proper usage is:
1. Do the action (open a page / click a button / ...)
2. Wait until the action is completed (a header appeared / a loading indicator disappeared / ...)
3. And only now you can run `$$.shouldBe(empty)`.

Step 2 is crucial. You need to be sure that the loading is completed. Otherwise step 3 may give a false positive.

**Comment by realulim** [comment]
I see your point, but in most UIs that I deal with there is no Step 2. The rows in the table appear within 100-200ms and no designer bothers putting up an indicator for that. size(1) has the same problem, btw, if the initial state is 1 row shown and you want to make sure no additional rows appear or that row 1 does not disappear.

So the actual task here is to test that an initial state does not change within a certain amount of time. Putting in a sleep(4000) does the job, but it would be more elegant and also safer to have an API for that.

The concrete motivation for me to suggest that is that I had a test that has been working for years, although the UI was really buggy. The test was written with a shouldBe(empty) and that was always true, even though the UI did load additional rows afterwards. Now you could say the test was buggy, but you could also say that this was the obvious API to use. The test looked perfectly logical:

* click button1, expect 3 rows to appear, reset
* click button2, expect 5 rows to appear, reset
* click button3, expect 0 rows to appear

Most tests in Selenide test for a change and it seems obvious to everyone that you will wait up to 4 seconds for the change to occur. So if you test for "no change" you kind of expect the same behavior. It literally makes no sense to test for "no change" and then not wait.

So in a sense we probably have a bigger API issue here that does not only have to do with "size". It would also happen for "appears", if a button appears initially and then disappears again within a second. So maybe we could have an API like this:

$(".myButton").click();
$$(".row").shouldRemain(empty);

The "remain" verb would check the condition, then wait for the configured timeout and then check the condition again.

**Comment by asolntsev** [comment]
@realulim Yes, `shouldRemain(empty)` sounds better. At least it gives a hint to users that this command will wait for some time.

But don't you see a problem that your tests will always spend 4 seconds just for some waiting? It makes your tests significantly slower. Isn't it a problem?

Looking at your flow, I see one problem in step 3:
1. click button1, expect 3 rows to appear, reset
2. click button2, expect 5 rows to appear, reset  // here table has 0 rows
3. click button3, expect 0 rows to appear            // here table has 0 rows

After performing step 2, your table has 0 rows. And after clicking `button3`, the table still has 0 rows. Nothing happens as a result of clicking `button3`. This is the root cause that makes the test flaky. You never know if the table is empty
1. because `button3` did it empty, or 
2. because it was already empty after step 2. 

Sleep doesn't really solve this problem. Sleep only increases probability of (1) over (2). But doesn't give a guarantee. 

One simple option would be to remove the "reset" in the end of each step. Then you know for sure that before step 3 the table was not empty, and it become empty as a result of clicking `button3`.

**Comment by realulim** [comment]
Yes sure, you are right. For this example I simplified the test, in reality the reset is a "user logout, next user login" operation. The test basically checks if certain users can load an appropriate amount of data. And there's one user that cannot load any at all. I have no problems with waiting 4 seconds there, as it is just one test in an entire test suite that runs 20 minutes anyway. And I simply have no other choice than to wait some time, if I want to test for "no change".

So yeah, since it's just one place where I need it, I might as well add the sleep(4000) there.

**Comment by realulim** [comment]
Here's another use case:

Suppose we have 10 elements with classname "myButton". Now we delete one of them and want to see the number reduced by one. The natural test would be:

```
int origCount = $$(".myButton").size();
// delete one button
$$(".myButton").shouldHave(size(origCount - 1));

```
If I'm not mistaken, then this test is flaky, because (origCount - 1) could be reached before the end of 4 seconds and return as true, even if more buttons were actually present.

**Comment by asolntsev** [comment]
> The natural test would be:

For me, the natural test would be:
```java
$$(".myButton").shouldHave(size(10));
// delete one button
$$(".myButton").shouldHave(size(9));
```

> even if more buttons were actually present.
What do you mean? There was 10 element, and you deleted one - but it results in appearing few more elements on the screen? How is it possible? Probably you performed some other actions in addition to clicking the "delete" button?

Anyway, it can happen with absolutely any test:
1. Your test asserts something like `assert FOO = 3`
2. After some time, `FOO` value changes to 4. 

In that sense, all tests in the world are flaky.

**Comment by realulim** [comment]
I kind of like my test, because it works with any number of buttons, not just 10. So when we decide to have 11 or 12 buttons, it will still test the button removal function correctly. This is frequently an issue, when you are running a large test suite and some tests fail and thus cannot clean up properly. Then the next test in the suite might start from a different baseline, so it is sometimes a good idea to establish the baseline dynamically and not rely on a static number.

But the flakiness I was referring to is a different issue: we essentially have no control over **when** $$ will count. So after I delete a button, the count might still be 10, because it takes a while to remove the button. And vice versa, if timing sucks, then the counting could stop at 9, when really there are 10 (e. g. some frameworks re-arrange the DOM).

So if our button removal function has stopped working, we might not notice. If every button has a unique ID, then we can check for this ID to disappear and that will work reliably, because it will wait for the entire 4 seconds. But if we count, we might count at an awkward point in time.

**Comment by asolntsev** [comment]
@realulim Yes, it's a valid idea not to hardcode 10, and use some dynamic value instead.
**BUT** it's important to take this value not from UI. You can get it from your own fixture (yml/xml/json/excel file), or database, or rest api. From any source you can trust. 

Remember:
> When you test UI - you are not allowed to trust UI.

_May be you got 10 from UI, but at the next millisecond there appeared one more element?_

> So after I delete a button, the count might still be 10, because it takes a while to remove the button.
This problem is already solved in Selenide. In this case, command `$$.shouldHave(size(9))` will wait for few seconds until the element gets removed. 


> But if we count, we might count at an awkward point in time.
Yes, we might. As I already said, it's possible with any tests. There is no guarantee against it. No one framework can protect us from this (potential) problem.
