### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by TomaszSzyborski** [selenide/selenide#2336]
## The problem
open(url, domain, login, password) like described in the examples 
```java
open("/basic-auth/hello", "", "scott", scottPassword());
$("#greeting").shouldHave(text("Hello, scott:" + scottPassword()));
```
doesn't work

only following code seems to do the trick:

```java
open(url);
((HasAuthentication)Selenide.webdriver().object()).register(login, password);
```

## environment
* **Selenide Version**:  6.15.0
* **Chrome**: 114.0.5735.111

**Comment by asolntsev** [comment]
@TomaszSzyborski What exactly means "doesn't work"?
There is a test in Selenide project, and it **works**:
https://github.com/selenide/selenide/blob/main/statics/src/test/java/integration/BasicAuthTest.java#L9

**Comment by TomaszSzyborski** [comment]
@asolntsev my bad, I should be more specific:
in my case. When using BasicAuth from Selenide I end up with Chrome BasicAuth modal opened after opening the browser.
It may be implementation specific - as the auth is needed for one domain that redirects immediately to another, so the only working way for me.

I tried opening: something.domain.com with BasicAuth (the BasicAuth modal does not appear), then opening other.domain.com - the BasicAuth modal says : other.domain.com (the domain.com portion remains the same), but the url in the browser stays something.domain.com

Entering the data manually works as well.

**Comment by asolntsev** [comment]
@TomaszSzyborski I think the problem is with domain. You open domain `something.domain.com` with BasicAuth, but it opens some resource (iframe or image?) on another domain `other.domain.com` that actually requires BasicAuth. Current Selenide mechanism just adds username+password to current URL (`something.domain.com`), so it doesn't help with different domains. 

But I will try to add your trick with `HasAuthentication` to Selenide code.

**Comment by asolntsev** [comment]
fixed in https://github.com/selenide/selenide/pull/2358
