### ISSUE TITLE
Test execution gets stuck when the 2nd open(String, Class<PageObjectClass>) is performed in the same Chrome/Edge instance

### ISSUE THREAD

**Issue by extryd** [selenide/selenide#2424]
## The problem
When I perform Selenide.open(String, Class<PageObjectClass>) the second time in the same Chrome/Edge instance, then test execution gets frozen forever without any errors/exceptions.

## Details
Is reproduced in Chrome and Edge only. In Firefox everything works fine.
Also, the issue appeared from updating to 6.17.0 Selenide version.

## Tell us about your environment
* **Selenide Version**: 6.17.0
* **Chrome\Firefox\IE Version**: Chrome 116.0.5845.97 / Edge 115.0.1901.203 / Firefox 116.0.3
* **Browser Driver Version**: 116.0.5845.96 (provided by SeleniumManager)
NOTE! Shows WARNING: Unable to find an exact match for CDP version 116, so returning the closest version found: 115 during the test execution
* **Selenium Version**: 4.11.0 (provided by Selenide)
* **OS Version**: Windows 10 19045.3208

## Code To Reproduce Issue
```
    @Test
    public void test() {
        Selenide.open("https://www.google.com/", Google.class);
        Selenide.open("https://www.google.com/", Google.class);
    }
```

**Comment by asolntsev** [comment]
@extryd Thank you for reporting the problem. You short reproducible sample was **extremely useful**. _Thumbs up!_

After an investigation, I came to a conclusion that it's actually a [bug in Webdriver](https://github.com/SeleniumHQ/selenium/issues/12576).  I managed to create a [reproducible example in pure Selenium](https://github.com/asolntsev/selenium-deadlock).

Though, we can tune Selenide code so that this problem will not affect most of Selenide users (but not all).
