### ISSUE TITLE
Delete WARN com.codeborne.selenide.impl.SelenidePageFactory - Cannot initialize field private com.codeborne.selenide.SelenideElement com.codeborne.selenide.ElementsContainer.self

### ISSUE THREAD

**Issue by DaniilMoiseevPenza** [selenide/selenide#2439]
When run tests with PageFactory selenide write strange warning:

```java
WARN SelenidePageFactory - Cannot initialize field private com.codeborne.selenide.SelenideElement com.codeborne.selenide.ElementsContainer.self
```

**Comment by asolntsev** [comment]
P.S. An additional detail from telegram chat: "Usually it happens when ElementContainer is bound to page object itself, not for its element". (?)

**Comment by asolntsev** [comment]
Hi @DaniilMoiseevPenza .

I realised that this WARN happens when you add `extends ElementsContainer` to a page object.
In this case, it's just not needed. You should remove `extends ElementsContainer` from page object.

You really need to add `extends ElementsContainer` only to elements that are annotated with `@FindBy`, but are not `WebElement`.

For example,

```java
  private static class MyPage extends ElementsContainer {  // NOT NEEDED, remove it.
    @FindBy(css = "#apostrophes-and-quotes")
    MyContainer container;
  }

  private static class MyContainer extends ElementsContainer { // NEEDED
    SelenideElement headerLink = $("h2>a");
    ElementsCollection options = $$("#hero>option");
  }
```
