### ISSUE TITLE
Selenide+Appium+Flutter

### ISSUE THREAD

**Issue by Gelsendorf** [selenide/selenide#2694]
![Знімок екрана 2024-03-22 113001](https://github.com/selenide/selenide/assets/72403586/f717bec5-ae35-45e1-91ba-7d31adb18c98)
Hi, has anyone had the problem of not being able to click on the widget? Widgets have their own locators, as in the example in the picture, but the locator is not found. How to write tests for Flutter in Selenide and Appium? Thanks

**Comment by asolntsev** [comment]
@Gelsendorf I didn't try it by myself, but yes, Selenide should work with Flutter apps.

Because there is Flutter implementation of WebDriver:
* https://github.com/appium/appium-flutter-driver
* https://github.com/ashwithpoojary98/javaflutterfinder
* https://www.lambdatest.com/blog/automating-flutter-apps-using-appium-flutter-driver/

**Comment by Gelsendorf** [comment]
I solved this problem in this way and it worked.

List<WebElement> elements = driver.findElements(By.xpath("//*[contains(@content-desc, 'Appium doctor')]"));
        for (WebElement element : elements) {
            element.click();
            sleep(8000);
        }

**Comment by asolntsev** [comment]
thank you for sharing the information.
