### ISSUE TITLE
Scroll methods unexpected behavior

### ISSUE THREAD

**Issue by ASTRO-CZ** [selenide/selenide#2850]
## The problem
SelenideElement methods for scrolling to element (scrollIntoView, scrollTo) instead of scrolling to element as expected only "jerk" the scrollbar two times by couple pixels and ends the action resulting in failing tests as following conditions are able to be fulfilled.

## Details
I have recently again started working on my company FE project and after updating both Selenide and Chrome (I use portable Chrome for test, in case its relevant) to latest, I started observing that my tests fail due to element not being visible. This is caused by this weird behavior where it doesnt scroll/drag the scrollbar properly and instead it just pulls it a little bit down couple pixels.

## Tell us about your environment
* **Selenide Version**:  7.4.3
* **Chrome\Firefox\IE Version**:  Chrome for Test 129.0.6668.58 (r1343869) * 
* **Browser Driver Version**: auto-managed
* **Selenide-Appium Version**: none
* **IOS\Android\WEB version**: none
* **Selenium Version**: whatever is baked into Selenide release
* **OS Version**: Win 11  

\* https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by ASTRO-CZ** [comment]
Sorry for spam, seems to be fixed now. App has lot of shadow doms and it seems that Xpath selector wasnt working as intended which caused issues for scrolling.

**Comment by asolntsev** [comment]
@ASTRO-CZ I have no idea how to reproduce this issue... Nobody knows.
If you want the problem to be fixed, describe how can other reproduce it.

**Comment by ASTRO-CZ** [comment]
@asolntsev hello and thanks for answer, normally I would provide more information, but I am not sure how much I can share without causing potential security incident at my work.  I will update the topic once I figure out what all can be posted publicly

**Comment by MatteoPalese** [comment]
@asolntsev I'm having the same problem and I want to share some information that may help solve this issue.

At first I assumed the mouse position was affecting the scroll, so I tested a bunch of times with it, but nothing happened. I noticed the test worked three times in a row before the pixel jerking started again. I've also tried scrollIntoView(), executeScript("arguments[0].scrollIntoView(true);", selenideElement), but the behaviour remains inconsistent. 

I hope this can help.

**Comment by asolntsev** [comment]
@MatteoPalese Sorry, but it can help only if we get a **reproducible example**. ¯¯\_(ツ)_/¯¯

**Comment by asolntsev** [comment]
Feel free to reopen the issue if we get info how to reproduce it.

**Comment by USSQA** [comment]
I was able to reproduce this behavior on a public website — could the maintainers consider reopening for investigation?

# Minimal, Reproducible Example For #2850

Selenide fails to scroll an off-screen element fully into view using `shouldBe(interactable)` / `.click()`, resulting in element click intercepted exception. Scroll only moves a few pixels (“jerks”), similar to the original report.

## Environment:

- Selenide v7.10.0
- Google Chrome Version 140.0.7339.128 (Official Build) (64-bit)
- Windows 11 (Also tested on Alpine Linux 3.22 with latest Chromium/Chromedriver and got the same result)
- WebDriver auto-managed by Selenide
- Headless vs Headed does not make a difference

## Minimal Example:

```java
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.Selenide;
import static com.codeborne.selenide.Condition.interactable;

public class DemoScrollBug {
    public static void main(String[] args) {
        Configuration.browserSize = "1920x1080";
        Selenide.open("https://www.microsoft.com/en-us/microsoft-365/online-surveys-polls-quizzes");
        Selenide.$x("//button[span[contains(text(), 'Organize your life')]]")
                .shouldBe(interactable)
                .click();
    }
}
```

## Observed behavior

`Exception in thread "main" Invalid element state [By.xpath: //button[span[contains(text(), 'Organize your life')]]]: element click intercepted: Element is not clickable at point (362, 1663)`

- The scroll only moves a few pixels (“jerks”) and fails:
  ![Image](https://github.com/user-attachments/assets/351b76d4-6145-4e87-990b-be4198a95e89)
- Using .scrollIntoCenter() manually allows the click to succeed:
  ```java
  Selenide.$x("//button[span[contains(text(), 'Organize your life')]]")
          .shouldBe(interactable)
          .scrollIntoCenter()
          .click();
  ```

## Expected behavior

Automatic scrolling should fully bring the element into view without needing .scrollIntoCenter().

**Comment by rosolko** [comment]
@USSQA I've just tried using the `scrollIntoView` method before the `interactable` check, and it works:
```java
Selenide.$x("//button[span[contains(text(), 'Organize your life')]]")
            .scrollIntoView(ScrollIntoViewOptions.instant())
            .shouldBe(interactable)
            .click();
```

**Comment by asolntsev** [comment]
@USSQA Thank you for the example!
Seems this issue is related to Selenium webdriver, not Selenide.
Look, I can reproduce the same problem with Selenium:

```java
  @RepeatedTest(10)
  void seleniumClickWithScroll() {
    //WebDriver driver = new ChromeDriver();
    WebDriver driver = new FirefoxDriver();
    try {
      driver.manage().window().setSize(new Dimension(1920, 1080));
      driver.navigate().to("https://www.microsoft.com/en-us/microsoft-365/online-surveys-polls-quizzes");
      driver.findElement(By.xpath("//button[span[contains(text(), 'Organize your life')]]")).click();
    }
    finally {
      driver.quit();
    }
  }
```

According to the [click specification](https://w3c.github.io/webdriver/#element-click), method `click` should scroll the element into view, but it doesn't. **Would you mind registering an issue in Selenium?** (https://github.com/seleniumHQ/selenium/issues/)

P.S. As from Selenide side, we suggest means to workaround the issue. You can call `scrollIntoView` before the click - and it works. :)

**Comment by mwdle** [comment]
The issue has been filed [https://github.com/SeleniumHQ/selenium/issues/16345](https://github.com/SeleniumHQ/selenium/issues/16345).
As a formality, can someone with permissions remove the `cannot reproduce` labels from this issue?

**Comment by asolntsev** [comment]
@ASTRO-CZ @MatteoPalese @USSQA @mwdle Ok, now we know the workaround (from that issue):
```java
Configuration.browserCapabilities = new ChromeOptions().addArguments("--disable-smooth-scrolling");
```

Probably we should add argument `"--disable-smooth-scrolling"` in Selenide by default for all chromium-based browsers?

**Comment by mwdle** [comment]
That seems like a reasonable solution to me, though the issue does also affect Firefox and it's unclear whether there's a similar workaround for it

**Comment by asolntsev** [comment]
@mwdle Agree. We should find a similar option for Firefox.

NB! Just in case, you can always call Selenide's method to scroll without effects:
```java
$.scrollIntoView(instant().block(center));
```

**Comment by asolntsev** [comment]
@mwdle I found an option for FireFox as well (but not for Safari):

https://github.com/selenide/selenide/pull/3119
