### ISSUE TITLE
Add failing for shouldNotHave* operations for not existing elements.

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#368]
Let's look at the two typical cases.

Case 1 tests closing the dialog.
Case 2 should check, if "reserved" text disappeared from some element, element itself should stay.

```
// case 1
dialogCloseButton.click();
// no matter, if deleted from DOM, or made invisible by CSS - should work the same, so ->
// okay
dialog.should(disappear); 
dialog.shouldBe(invisible);
dialog.shouldNotBe(visible);

//case 2
seatInformation.shouldHave(text(„reserved"));
cancelSeatReservationButton.click();
// seatInformation may not be deleted or made invisible -> it should show error
// error
seatInformation.shouldNotHave(text(„reserved"));
```

For Case 1, if dialog element itself disappers from DOM, it looks that Selenide works just fine not failing here.

At the moment in Case 2, if seatInformation element disappears completely, which is in the most cases undesired behavior, the test passes nevertheless. It can be fixed with:

```
seatInformation.shouldHave(text(„reserved"));
cancelSeatReservationButton.click();
seatInformation.shouldBe(visible).shouldNotHave(text(„reserved"));
```

But this shouldBe(visible) check is necessary for probably >99% all shouldNotHave() cases, so Selenide could implement it as default behavior and fail if seatInformation not exists/not visible.

**Comment by hujog** [comment]
I strongly disagree to "For Case 1, if dialog element itself disappers from DOM, it looks that Selenide works just fine not failing here.".
Visibility requires existence. Non-existing objects cannot have any other feature than their non-existence.


An synthetic example from the OO design of "the ontology" of everything: You have entities and entities have features. (entity: https://en.wikipedia.org/wiki/Entity)
Only material entities can have a colour. Non-material entities like a story or hate cannot have a colour.
Should myHate.is(red) or yourstory.isnot(green) or myHate = yellow result in anything else than an exception?!
They must throw an exception! Concepts (non-physical entities in my synthetic example) do not have a colour - as non-existant DOM-objects do not have a visibility.

(I would be less agitated about this if I had not recently read code that naturally implied existence when it checked "redFlyingElephant.shouldNotBe(visible)" and was not knowing that this code just translated to "true" and was not checking that "redFlyingElephant" was invisible but was checking that if "red flying elephant" would exist it would be invisible (and always return "true" if you were just wacky, thinking of a red flying elephant ever existed anywhere))

**Comment by asolntsev** [comment]
@hujog I totally understand your point of view. It's logically incorrect to check if element A is visible or not if A just doesn't exist. 

But let's look from pragmatic point of view. Test must not be tightly coupled with implementation, right? 
From the point of test, WHAT is important, but HOW is not important. 
E.g. test wants to check that text "Please log in" disappears after login. It doesn't matter HOW it's implemented: either element is removed from DOM, or it just gets hidden by CSS. User doesn't see it anymore - it's the only important aspect. 

There are some cases where it's really important to check that element does not exist even in DOM (e.g. if element contains some sensitive data like password). I assume it's a rare case, but it's possible to check it with `$(By.name("password")).shouldNot(exist)`.

**Comment by asolntsev** [comment]
@vinogradoff Yes, probably `seatInformation.shouldNotHave(text(„reserved"))` should fail if `seatInformation` doesn't exist. Seems reasonable. But I am afraid it can break lot of existing tests. 

Probably we can assume that it's the responsibility of the test author to verify that `seatInformation` is still visible if it's really important.

**Comment by hujog** [comment]
> @hujog I totally understand your point of view. It's logically incorrect to check if element A is visible or not if A just doesn't exist.
> 
> But let's look from pragmatic point of view. Test must not be tightly coupled with implementation, right?

@asolntsev I get your point of view and we are at the point of "agree to disagree" here it seems. (Aka: I will shut up. You are leading the development of this framework! (but I still want to stress some points))
"Tests tightly coupled with implementation": I don't understand this point; I don't understand where a test is coupled to the implementation if a test framework says "yeah, "X is not displayed" when the fact is "X is not existent".
Back to the "philosophical difference" between us: If I want to check for something on an element and it does not exist I want an error, "ElementDoesNotExist", not "yeah, ask me something about a non-existing element and I will say "Yes". Why? Because the former tells me what is wrong the later just adds confusion (When I, as a human who writes a test for feature Y on element X I **assume that element X is existant**, otherwise I would not check for feature Y on it).
To @vinogradoff s post "probably seatInformation.shouldNotHave(text(„reserved")) should fail if seatInformation doesn't exist. Seems reasonable. But I am afraid it can break lot of existing tests.": An existing test that relies on an non-existant element to not have some feature is useless. This behaviour (if I understand the current behaviour correctly) is hiding facts. Tests are for displaying facts.

I am not arguing about "element is existant in the DOM" or "element is existing in the DOM but not visible". For that (exists but is invisible) I totally agree with you @asolntsev, this is not a task for the test framework, I am only talking about "fail any feature request for an element if it does not **exist**".
<stepping off soap box>

**Comment by asolntsev** [comment]
@hujog Sure, I don't want anybody to shut up :) 
I understand what you are talking about. I find it reasonable. But I also find reasonable the other opinion. So it's just hard to choose one. 

Let me explain what I mean "Tests tightly coupled with implementation". 
For business, it's only important that "password" field is hidden. This is WHAT - hidden.
And it's not important HOW it's achieved. It can be achieved either by CSS property `display: none` or by removing the node from HTML. In both cases, the business goal is achieved. 

Let's assume that developers are changing this algorithm with every release. Yesterday they removed the node, today they use CSS, tomorrow they will remove the node again. In your case, you will need to waste time and fix your tests every time. While the functionality is not broken. Do you really think it's a good idea to waste time because of non-functional changes? This is what I call "tightly coupled with implementation". 

Test WHAT, not HOW.

**Comment by asolntsev** [comment]
@hujog Please, don't shut up! :) Good solutions are born in discussions.

I have got one more argument. 
Should those 2 operators have the same effect?
1. `$x("//div/span").should(...);`
2. `$x("//div").$x("./span").should(...);`

It seems reasonable for me that these 2 lines work exactly the same (except one corner case when we have multiple `<div>` on the page, and first of them doesn't contains `<span>`). 

But your suggestion implies that they will work differently.

**Comment by hujog** [comment]
I still get your arguments (now also what you mean with "tight coupling" in "password field hidden" example) but still think different. Probably because the tests I write are written with a different goal or mindset.
In your example you want to not fail a test if the way the password field is hidden uses a different technique. You think about "password field is not visible to the user" as the WHAT.
That would be a test to verify that a password field is not visible/usable by a typical user and thinks more from the application side.
The tests that I do with a UI are thinking from the user. I want to _use_ an element like a user would do and rarely test for not_visible OR not_existant OR size_0_0 to check if something is NOT there for the user.
So if I want to _use_ the element I cannot use it if it is not there. If I check e.g. the text of something that does not exist, I absolutely want that test to fail since I am emulating a user in my tests and most of the time use UI automation for positive tests.
If the element is not there -> Fail!
That is exactly what I want. The user cannot interact with it in any way, so this test must fail. The test framework should not make decisions or assumptions (my point of view).
If the element is hidden ... bad luck for my test. It still has text and my test would wrongly pass. That is the reason why I write little helper functions like find_single_visible_element() a lot. 
Different Javascript frameworks and different developers tend to do the same WHAT by a different HOW (and before the garbage collector cleaned up you may even work on elements that logically no longer should exist), but my tests should still work if it works for a user and still fail if it does not work for a user. Such helper functions helped me a lot in fixing flaky tests (and even the garbage collector is - alas - not a theoretical but a practical example ... a second element would be still there for 2 more seconds or not, so the timing of the testrunner would determine if it found only 1 element (if the garbage collection already happened) or 2 and the first being the wrong one).

Oh, one note on "But I am afraid it can break lot of existing tests.". I agree but tests failing after this change have been useless already. They need to be fixed or removed since saying "yes" to "my house is painted green?" when the house does not even exist ... stipulates a non-existing house! I don't want tests for the color of a non-existing house to pass.
(I don't know how others design there tests, so I may be wrong about this but for the way I design tests I would absolutely love a change in the test framework that points me to useless tests.)

And, BTW, you created a really nice test framework with Selenide! No doubt about that and thank you very much!!

**Comment by asolntsev** [comment]
@hujog Wait, it seems you are missed something.
1. You are talking about **positive case**, and I am absolutely agree with this. 
   The line `$("#house").shouldBe(green)` must fail if the house doesn't exist. 
   And it fails. There is no problem here.
2. But the whole discussion is about **negative case**:
   `$("#house").find(".roof).shouldNot(exist)`

My point is that this line should not fail if even house doesn't exist. (If you want to be sure that only roof is missing, but house exists, you can write `$('#house").should(exist)`).

Are we in sync? Are you also talking about the negative case?

**Comment by IsakovRoman** [comment]
Let me add some info to the topic. Assuming I want to check that specific element must have something(ex. text) - **first case** and it must not have text - **second case**

In both cases I intentionally set invalid locator

**First scenario**

`
open("https://www.google.com");
$("input1").shouldHave(text("Search"));
`

**Traceback:**

> Element not found {input1}
> Expected: text 'Search'
> Screenshot: file:/home/roman/IdeaProjects/test/build/reports/tests/1578989246849.0.png
> Page source: file:/home/roman/IdeaProjects/test/build/reports/tests/1578989246849.0.html
> Timeout: 4 s.
> Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"input1"}

Seems OK, because element was not found and test case failed due reason above.


**Second scenario**
`
open("https://www.google.com");
$("input1").shouldNotHave(text("Search"));
`
**Traceback:**
> INFO  com.codeborne.selenide.webdriver.WebDriverFactory  - BrowserName=chrome Version=78.0.3904.108 Platform=LINUX
> INFO  com.codeborne.selenide.webdriver.WebDriverFactory  - Selenide v. 5.5.1
> INFO  com.codeborne.selenide.webdriver.WebDriverFactory  - Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
> INFO  com.codeborne.selenide.drivercommands.CreateDriverCommand  - Create webdriver in current thread 16: ChromeDriver -> ChromeDriver: chrome on LINUX 
> debug.Test > check() **PASSED**

As you can see, test passed because of **shouldNotHave** , though I expect TC to fail. My logic is that I could not assert that specific element does not have text -> fail TC.

**Summary**
I see that people have different point of views on this subject. Could we just implement option for Selenide Configuration with boolean (?) value to set shouldNot bahavior?

**Comment by asolntsev** [comment]
@IsakovRoman @hujog I tend to think that we need to change the current behaviour. 
For me, it's a strong argument that this code: 

```java
$("input1").shouldNotHave(text("Search"));
```

would work with invalid locator, making it **too easy** to forget it _occasionally_ (when renaming locators in other places).

**Comment by vinogradoff** [comment]
Next discussion point:

```java
$("input1").shouldNotBe(visible);
$("input1").shouldNot(exist);
```

must tests stay "passed" or not?
A lot of users  check the disappearance this way.

Or must they migrate to this?

```java
$("input1").shouldBe(hidden);
$("input1").should(disappear);
```

**Comment by asolntsev** [comment]
@vinogradoff I don't understand what you are talking about :)

Given that "input1" doesn't exist in DOM, all these are synonyms:
* `$("input1").shouldNotBe(visible);`
* `$("input1").shouldNot(exist);`
* `$("input1").shouldBe(hidden);`
* `$("input1").should(disappear);`

P.S. `should(disappear)` may seem natural in situation when the element existed before a click, and you did a click, and the element is expected to disappear as a result of the click.

**Comment by asolntsev** [comment]
Done in https://github.com/selenide/selenide/pull/1116
