### ISSUE TITLE
Implement exported to Selenide code from Selenium Builder

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#370]
Suggested by [Charlie Eakins](https://twitter.com/Charles_Eakins):

> @jselenide Any plans to add export for selenide from Selenium Builder? 
> Would be great, management wants none dev to be able to record test

I don't imagine how to implement it yet, but the idea is great. It will allow lot of people to migrate to Selenide.

**Comment by kpyfan** [comment]
@asolntsev Along the same vein, would be nice to have for SeleniumIDE since that is the official tool. Also, is there any resource for taking existing selenium tests and migrating them to Selenide?

**Comment by asolntsev** [comment]
@kpyfan Unfortunately I don't know such a tool. I guess in most cases this tool would not give a big benefit because people often have an over-complicated Selenium code (grouped somehow into helper methods, "page objects", "steps", "frameworks" etc). If converted automatically to Selenide, such code would still be over-complicated. I think people need to learn refactoring and clean code.

Thought, I could write a post about refactoring tools in IDEA that can help people in this way.

**Comment by kpyfan** [comment]
I would be very interested in a blog post about how to get started that way. Right now my team actually has all of its existing tests in Selenide (we did a big rewrite a year or two ago). We're looking to add test coverage in places that are being missed, but we want to go the easier route of having test code generated from browser interaction rather than having to write everything out manually. Unfortunately, the only generator that seems to be working is the SeleniumIDE, which would output Selenium that we'd have to translate into Selenide. We're thinking about writing a Perl script or something along those lines to translate the output.

**Comment by asolntsev** [comment]
@kpyfan Hi, we have a great news!

@dstekanov Implemented Selenide exporter for Selenium IDE. 

We have published version 0.1.1 for beta testing. Can you give it a try?
* [firefox](https://addons.mozilla.org/en-US/firefox/addon/selenide-for-selenium-ide/)
* [chrome](https://chrome.google.com/webstore/detail/selenide-for-selenium-ide/nlkfobhoffngaakgdbkdnmmjcchibcba)

**Comment by asolntsev** [comment]
version 1.0.0 was released. Yuhuuu!
