### ISSUE TITLE
IndexOutOfBounds if CollectionElement used as context does not exist

### ISSUE THREAD

**Issue by CaBocuk** [selenide/selenide#747]
## The problem
If you use not existing CollectionElement as search context for a collection -> IndexOutOfBounds is thrown

## Details
Such code for looking for Collections
```Java
    @Test
    public void test () {
        open("https://yandex.ru");
        $$("not-existing-locator").first().$$("locator").isEmpty();
    }
```
Produces `java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0`

But same logic for looking for Elements
```Java
    @Test
    public void test () {
        open("https://yandex.ru");
        $$("not-existing-locator").first().$("locator").exists();
    }
```
Works fine. And `$$("not-existing-locator").first().$("locator").exists();` has `false` value.

Seems to have some kind of inconsistency. Does it work as designed?

## Tell us about your environment
**Selenide Version:** 4.11.4

**Comment by sidelnikovmike** [comment]
hm. Code fails on `first()` I think. You are trying to get first element of list with size = 0. It is java common behaviour.

**Comment by CaBocuk** [comment]
@sidelnikovmike sure it is, but it works fine for `$$("not-existing-locator").first().$("locator").exists();`
and this different behavior is a bit confusing imo

**Comment by asolntsev** [comment]
@CaBocuk I think that different behaviour is a bit confusing, but not critical at all.

BUT

If I modify your sample a bit, we get a real problem. The line below line should not throw an exception, but throws. And this is a bug in Selenide. We need to fix it. 

```java
$$("not-existing-locator").first().$$("locator").shouldHave(size(0)); 

// for comparison, the equivalent line for a single web element works fine:
$$("not-existing-locator").first().$("locator").shouldNot(exist);
```

**Comment by Denysss** [comment]
@asolntsev 
1. What do you think about this case?
`$("not-existing-locator").$$("#multirowTable").shouldHaveSize(0);`
It throws
`Element not found {not-existing-locator}`
`Expected: exist`
`NoSuchElementException: Unable to locate element: not-existing-locator`
and it's clear as for me.

2.  What is expected behavior for the discussed cases?
`$$("not-existing-locator").first().$$("locator").shouldHave(size(0));`
`$$("not-existing-locator").first().$("locator").shouldNot(exist);`
I believe they should throw `NoSuchElementException: Unable to locate element: not-existing-locator` too.

**Comment by asolntsev** [comment]
@Denysss We have two options:
1. It should throw exception because parent element `$("not-existing-locator")` doesn't exist.
2. It should work without errors because collection `("not-existing-locator").$$("locator")` IS empty, and `....shouldHaveSize(0)` IS true. 

I personally think that the 2nd option is better. At least this is consistent with `$` behaviour.
