### ISSUE TITLE
Add possibility to choose collection reload strategy

### ISSUE THREAD

**Issue by kalumpiwarra** [selenide/selenide#815]
After reverting collection behavior to the reload collection on each call (except iterators), new issues appear / performance significantly decreased in a few cases.

I faced with two cases after #696 (partially revert reloading collection on each call):

- During using of the new iterator, it's possible to face StaleElementReferenceException. Especially in cases when collection element was used during iteration, or used after iteration as search context. Example:
`$$x("//checkboxes").forEach(SelenideElement::click);` 
Here I would like to click on each checkbox. Such action has a high possibility of StaleElementReferenceException. 
I'm facing with it very often after switching to the version 4.14.1 (from 4.12.0). It looks like #797 describes such behavior.
- When I'm avoiding usage of iterators performance significantly decreased. Access to each element reloading collection from a browser. Example: in the case of a lot of collection usage (> 180) and search in the collection element as search context execution time increased from ~3min to ~12min.

Considering the above behavior, I would like to propose to implement a possibility to choose the collection reload strategy (configuration properties):
1. Default: as implemented now. Suitable in most cases
2. Lazy collection reloading: suitable in cases:
   - collection element may change during iteration
   - using of collection elements later as a search context

Selenide version: 4.14.1

**Comment by rosolko** [comment]
@kalumpiwarra Use `$$.snapshot()` to increase collection performance again. In this case you will work with cached collection.
From: https://selenide.org/2018/07/17/selenide-4.12.3/

**Comment by kalumpiwarra** [comment]
@rosolko I've got the same result on the second element: StaleElementReferenceException.
Looks like as underlayer both Iterator and Snapshot using fetch() to take an actual collection.
That's why I'm proposing to support two ways of working with collections.

**Comment by asolntsev** [comment]
@kalumpiwarra I investigated your issue a little bit. 
My resolution is that method `snapshot` works correctly. It returns a list of elements actual at that moment. If you later try to use one of these elements, but it has disappeared meanwhile, you must get `StaleElementReferenceException`. It's just not possible to do anything else. 

I suggest not to introduce "reloading strategy" because it would increase complexity. 
Instead, I suggest to change behaviour of `$$.iterator()` back to non-caching algorithm. Those who need performance can still call `$$.snapshot().iterator()`. 

Let's continue discussion in https://github.com/selenide/selenide/issues/797.
